UPDATE test_items AS t SET
  status = v.status,
  notes = CASE WHEN v.is_fail OR v.is_warn THEN v.note ELSE t.notes END,
  tester_name = CASE WHEN v.is_fail THEN 'سيد' ELSE t.tester_name END
FROM (VALUES
  ('REG-01', 'نجح', '', false),
  ('REG-02', 'نجح', '', false),
  ('REG-03', 'نجح', '', false),
  ('SW-01', 'نجح', '', false),
  ('SW-02', 'نجح', '', false),
  ('SW-03', 'نجح', '', false),
  ('SW-06', 'تخطي', '`components/dashboard-shell.tsx` فيه ألوان أخضر/ذهبي للمقرأة، و `components/academy-dashboard-shell.tsx` فيه `blue-500` للأكاديمية. **لكن** اللون المحدد `#1E3A5F` في مخطط التصميم مش مستخدم — الأكاديمية بتستخدم Tailwind `blue-500` اللي `#3b82f6`. لازم تتأكد بصرياً.', false),
  ('SW-07', 'نجح', '', false),
  ('MW-01', 'نجح', '', false),
  ('MW-02', 'نجح', '', false),
  ('MW-03', 'نجح', '', false),
  ('MW-04', 'نجح', '', false),
  ('MW-05', 'نجح', '', false),
  ('STU-01', 'فشل', '`app/student/page.tsx` بيرندر `<RecitationRecorder />` بس. **مفيش إحصائيات** (عدد التسميعات، آخر نشاط، المستوى) على الـ dashboard. الصفحة متطابقة مع `/student/submit`.', true),
  ('STU-02', 'فشل', 'API `app/api/prayer-times/route.ts` موجود لكن مش مستدعى في `app/student/page.tsx`. أوقات الصلاة لا تظهر على الـ dashboard.', true),
  ('STU-03', 'فشل', 'فيه cron `app/api/cron/werd-reminders/route.ts` لإرسال إيميلات، لكن مفيش widget «الورد اليومي» على صفحة `/student`.', true),
  ('STU-05', 'فشل', '`components/student/RecitationRecorder.tsx` **مفيش فيه حقل اختيار السورة**. الاعتماد كله على التسجيل الصوتي بدون metadata تفصيلية.', true),
  ('STU-06', 'فشل', '**مفيش حقل اختيار الآيات (من/إلى)** في الـ RecitationRecorder.', true),
  ('STU-07', 'نجح', '', false),
  ('STU-08', 'فشل', '**مفيش حقل اختيار نوع التسميع** (حفظ/مراجعة/تلاوة) في الـ Recorder.', true),
  ('RDR-01', 'نجح', '', false),
  ('RDR-14', 'نجح', '', false),
  ('ADM-03', 'نجح', '', false),
  ('ADM-06', 'نجح', '', false),
  ('ADM-07', 'نجح', '', false),
  ('ADM-09', 'نجح', '', false),
  ('ADM-13', 'نجح', '', false),
  ('ADM-14', 'نجح', '', false),
  ('ADM-15', 'نجح', '', false),
  ('ADM-16', 'نجح', '', false),
  ('ADM-17', 'نجح', '', false),
  ('ADM-18', 'نجح', '', false),
  ('ADM-19', 'نجح', '', false),
  ('ADM-20', 'نجح', '', false),
  ('ADM-21', 'نجح', '', false),
  ('ADM-22', 'نجح', '', false),
  ('ADM-23', 'نجح', '', false),
  ('ADM-24', 'نجح', '', false),
  ('ADM-25', 'نجح', '', false),
  ('ADM-26', 'نجح', '', false),
  ('ADM-27', 'نجح', '', false),
  ('ASTU-03', 'تخطي', 'الأكاديمية تستخدم `blue-500` Tailwind (`#3b82f6`)، المقرأة تستخدم `#0B3D2E` + `#D4A843`. التمييز موجود لكن اللون الأزرق المحدد في التصميم `#1E3A5F` مش مستخدم.', false),
  ('ASTU-04', 'نجح', '', false),
  ('ASTU-07', 'نجح', '', false),
  ('ASTU-10', 'نجح', '', false),
  ('ASTU-13', 'نجح', '', false),
  ('ASTU-14', 'نجح', '', false),
  ('ASTU-16', 'نجح', '', false),
  ('ASTU-17', 'نجح', '', false),
  ('ASTU-18', 'نجح', '', false),
  ('ASTU-19', 'نجح', '', false),
  ('ASTU-20', 'نجح', '', false),
  ('ASTU-21', 'نجح', '', false),
  ('ASTU-22', 'نجح', '', false),
  ('ASTU-23', 'نجح', '', false),
  ('ASTU-25', 'نجح', '', false),
  ('ASTU-26', 'نجح', '', false),
  ('ASTU-27', 'نجح', '', false),
  ('ASTU-28', 'نجح', '', false),
  ('ASTU-29', 'نجح', '', false),
  ('ASTU-30', 'نجح', '', false),
  ('ASTU-32', 'نجح', '', false),
  ('TCH-02', 'نجح', '', false),
  ('TCH-04', 'نجح', '', false),
  ('TCH-05', 'نجح', '', false),
  ('TCH-08', 'نجح', '', false),
  ('TCH-09', 'نجح', '', false),
  ('TCH-11', 'نجح', '', false),
  ('TCH-12', 'نجح', '', false),
  ('TCH-13', 'نجح', '', false),
  ('TCH-14', 'نجح', '', false),
  ('TCH-17', 'نجح', '', false),
  ('TCH-18', 'نجح', '', false),
  ('TCH-19', 'تخطي', '**مسار التيست مش متطابق:** التيست بيقول `/academy/teacher/create-students` — الموجود فعلياً `/academy/teacher/students/create` + `/academy/teacher/students/new`. الميزة موجودة لكن الرابط مختلف.', false),
  ('TCH-21', 'نجح', '', false),
  ('TCH-23', 'نجح', '', false),
  ('TCH-24', 'نجح', '', false),
  ('TCH-25', 'نجح', '', false),
  ('TCH-26', 'نجح', '', false),
  ('AADM-02', 'نجح', '', false),
  ('AADM-03', 'نجح', '', false),
  ('AADM-04', 'نجح', '', false),
  ('AADM-05', 'نجح', '', false),
  ('AADM-08', 'نجح', '', false),
  ('AADM-09', 'نجح', '', false),
  ('AADM-10', 'نجح', '', false),
  ('AADM-14', 'نجح', '', false),
  ('AADM-15', 'نجح', '', false),
  ('AADM-16', 'نجح', '', false),
  ('AADM-17', 'نجح', '', false),
  ('AADM-18', 'نجح', '', false),
  ('AADM-19', 'نجح', '', false),
  ('AADM-20', 'نجح', '', false),
  ('AADM-21', 'نجح', '', false),
  ('AADM-23', 'نجح', '', false),
  ('AADM-24', 'نجح', '', false),
  ('AADM-26', 'نجح', '', false),
  ('AADM-28', 'تخطي', 'المقارنة بين الـ shell الأخضر والـ shell الأزرق بتتم بصرياً فقط — الكود مختلف ومنفصل (dashboard-shell vs academy-dashboard-shell) ✅', false),
  ('PAR-03', 'نجح', '', false),
  ('PAR-07', 'نجح', '', false),
  ('PAR-09', 'نجح', '', false),
  ('PAR-11', 'نجح', '', false),
  ('PAR-13', 'نجح', '', false),
  ('PAR-14', 'نجح', '', false),
  ('SUP-01', 'نجح', '', false),
  ('SUP-03', 'نجح', '', false),
  ('SUP-07', 'نجح', '', false),
  ('SUP-10', 'نجح', '', false),
  ('SUP-12', 'نجح', '', false),
  ('SUP-15', 'نجح', '', false),
  ('DSG-01', 'نجح', '', false),
  ('DSG-02', 'تخطي', 'اللون المحدد `#1E3A5F` **غير مستخدم في الكود**. الأكاديمية تستخدم Tailwind `blue-500` (`#3b82f6`) و `blue-600` في `academy-dashboard-shell.tsx`. التمييز البصري موجود لكن اللون مش بالضبط حسب الـ design spec.', false),
  ('DSG-03', 'نجح', '', false),
  ('DSG-04', 'نجح', '', false),
  ('DSG-05', 'نجح', '', false)
) AS v(code, status, note, is_fail)
WHERE t.code = v.code;